import { describe, expect, it } from "vitest";
import type { ResumeLibraryDetail } from "@arc/shared/studio-resumes";
import {
  AI_INTERVIEW_LINK_VALIDITY_OPTIONS,
  getStoredInterviewQuestions,
  getStructuredLaunchConfirmation,
  requiresStructuredLaunchConfirmation,
} from "../launch-interview-dialog";

function makeDetail(overrides: Partial<ResumeLibraryDetail> = {}): ResumeLibraryDetail {
  // SAFETY: The helper supplies only the structured fields used by the pure confirmation rules.
  return {
    resumeEvaluationArtifactMode: "structured",
    structuredGateStatus: "failed",
    structuredResumeEvaluation: { runId: "run-1" },
    structuredScoreGrade: "unmatched",
    ...overrides,
  } as ResumeLibraryDetail;
}

describe("LaunchInterviewDialog structured launch confirmation", () => {
  it("offers permanent validity by default plus 1, 3, and 7 day choices", () => {
    expect(AI_INTERVIEW_LINK_VALIDITY_OPTIONS).toEqual([
      { label: "永久", value: "permanent" },
      { label: "1 天", value: "1_day" },
      { label: "3 天", value: "3_days" },
      { label: "7 天", value: "7_days" },
    ]);
  });

  it("requires confirmation for a below-threshold structured evaluation", () => {
    expect(requiresStructuredLaunchConfirmation(makeDetail())).toBe(true);
    expect(getStructuredLaunchConfirmation(makeDetail())).toEqual({
      gateStatus: "failed",
      grade: "unmatched",
      runId: "run-1",
    });
  });

  it("does not require confirmation when the evaluation is absent or passing", () => {
    expect(requiresStructuredLaunchConfirmation(null)).toBe(false);
    expect(
      requiresStructuredLaunchConfirmation(
        makeDetail({ structuredGateStatus: "passed", structuredScoreGrade: "matched" }),
      ),
    ).toBe(false);
    expect(getStructuredLaunchConfirmation(makeDetail({ structuredResumeEvaluation: null }))).toBe(
      null,
    );
  });
});

describe("LaunchInterviewDialog stored questions", () => {
  it("uses questions generated by the resume parsing worker", () => {
    expect(
      getStoredInterviewQuestions(
        makeDetail({
          interviewQuestions: [
            {
              difficulty: "medium",
              evaluationFocus: "系统设计",
              followUpDirections: "继续追问取舍",
              order: 4,
              question: "  请介绍一次系统设计经历  ",
            },
          ],
        }),
      ),
    ).toEqual([
      {
        difficulty: "medium",
        dimension: "business",
        evaluationFocus: "系统设计",
        followUpDirections: "继续追问取舍",
        order: 1,
        question: "请介绍一次系统设计经历",
      },
    ]);
  });

  it("returns null for legacy records without generated questions", () => {
    expect(getStoredInterviewQuestions(makeDetail({ interviewQuestions: [] }))).toBeNull();
  });
});
