"use client";

import { IconLoader2 } from "@tabler/icons-react";
// 真人面试准备弹窗：确认候选人的异步生成题目并落库，供真人面试官参考。
// 开弹窗时优先读取简历解析 Worker 已生成的题目；历史空数据才调用
// 工作区范围的 generate-questions 兜底。用户可继续增删改，
// 确认后由调用方原子保存题目并推进到真人面试阶段。
//
// Human-interview preparation dialog. On open, use questions generated by the resume
// parsing worker, falling back to the workspace-scoped generation route for legacy
// records. The caller persists the confirmed reference questions while advancing
// the candidate to the human-interview stage.

import { useForm } from "@tanstack/react-form";

import { m } from "motion/react";
import { useEffect, useRef, useState } from "react";
import { toast } from "sonner";
import { z } from "zod";
import { SortableQuestionListEditor } from "@/components/features/studio/sortable-question-list-editor";
import { ResumeProfileView } from "@/components/features/resume/resume-profile-view";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Field, FieldDescription, FieldLabel } from "@/components/ui/field";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { Modal } from "@/components/ui/modal";
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { env } from "@/env/client";
import { fetchStudioResume, launchInterviewFromResume } from "@/lib/client/api";
import { analysisStreamEventSchema, readAiRunEventStream } from "@/lib/client/ai-run-event-stream";
import { runAsyncAction } from "@/lib/client/async-control";
import { rpc } from "@/lib/client/rpc";
import { useWorkspaceSlug } from "@/lib/client/workspace-context";
import { generatedInterviewQuestionSchema } from "@arc/db-schema/interview/types";
import type { InterviewQuestion, ResumeProfile } from "@arc/db-schema/interview/types";
import type { ResumeLibraryDetail } from "@arc/shared/studio-resumes";
import type { AiInterviewLinkValidity } from "@arc/shared/interview/ai-interview-invitation";
import { ResumeOverviewPanel } from "./resume-overview-panel";

interface LaunchFormValues {
  interviewQuestions: InterviewQuestion[];
}

const EMPTY_FORM_VALUES: LaunchFormValues = { interviewQuestions: [] };
const streamErrorPayloadSchema = z.object({ error: z.string().optional() });
const streamQuestionsPayloadSchema = z.object({
  interviewQuestions: z.array(generatedInterviewQuestionSchema),
});
const launchDialogTabSchema = z.enum(["questions", "overview", "experience"]);

export const AI_INTERVIEW_LINK_VALIDITY_OPTIONS = [
  { label: "永久", value: "permanent" },
  { label: "1 天", value: "1_day" },
  { label: "3 天", value: "3_days" },
  { label: "7 天", value: "7_days" },
] as const satisfies readonly { label: string; value: AiInterviewLinkValidity }[];

export function requiresStructuredLaunchConfirmation(detail: ResumeLibraryDetail | null): boolean {
  return (
    detail?.resumeEvaluationArtifactMode === "structured" &&
    (detail.structuredGateStatus === "failed" || detail.structuredScoreGrade === "unmatched")
  );
}

export function getStructuredLaunchConfirmation(detail: ResumeLibraryDetail | null) {
  const runId = detail?.structuredResumeEvaluation?.runId;
  if (
    !requiresStructuredLaunchConfirmation(detail) ||
    !runId ||
    !detail?.structuredGateStatus ||
    !detail.structuredScoreGrade
  ) {
    return null;
  }
  return {
    gateStatus: detail.structuredGateStatus,
    grade: detail.structuredScoreGrade,
    runId,
  };
}

// 招聘台的「发起 AI 面试」只编辑题目，所以走最小化的 useForm；不要复用
// AI 面试侧的 useInterviewForm —— 它绑了 studioInterviewClientFormSchema，
// 会因为本弹窗里没有候选人姓名 / JD / 排期字段而静默 invalid 阻塞提交。
//
// We use a stripped useForm rather than useInterviewForm because the latter
// runs studioInterviewClientFormSchema which would silently fail on the
// candidate / JD / schedule fields this dialog doesn't expose.
function normalizeInterviewQuestions(values: InterviewQuestion[]): InterviewQuestion[] {
  return values.map((question, index) => ({
    ...question,
    evaluationFocus: question.evaluationFocus?.trim() || null,
    followUpDirections: question.followUpDirections?.trim() || null,
    order: index + 1,
    question: question.question.trim(),
  }));
}

export function getStoredInterviewQuestions(
  detail: ResumeLibraryDetail | null,
): InterviewQuestion[] | null {
  const questions = detail?.interviewQuestions ?? [];
  return questions.length > 0 ? normalizeInterviewQuestions(questions) : null;
}

interface HumanInterviewQuestionDialogProps {
  open: boolean;
  recordId: string | null;
  candidateName: string | null;
  onOpenChange: (open: boolean) => void;
  onConfirmed: (questions: InterviewQuestion[]) => boolean | Promise<boolean>;
}

/**
 * 流式调工作区范围内的 generate-questions，等到 result 事件取出 questions。
 * 失败时抛 Error 让调用方统一 toast。
 * Stream the workspace-scoped generate-questions route and pluck `interviewQuestions` from
 * the terminal result event; throws on stream-side errors so the caller can
 * toast uniformly.
 */
async function streamGenerateQuestions(
  slug: string,
  resumeProfile: ResumeProfile,
  signal: AbortSignal,
): Promise<InterviewQuestion[] | null> {
  // 用 hc 客户端调流式接口：URL 常量化 + body 类型推断走 zValidator schema；
  // body 自己 await 拿 Response 后用 readAiRunEventStream 读流（rpcFetch 会消费整个 body）。
  // Streaming via hc: URL + body types come from the zValidator schema. Consume
  // the stream manually because rpcFetch would parse the whole body.
  const response = await rpc.api.w[":slug"].interview["generate-questions"].$post(
    { json: { resumeProfile }, param: { slug } },
    { init: { signal } },
  );
  if (!response.ok) {
    const errorPayload = streamErrorPayloadSchema.safeParse(
      await response.json().catch(() => null),
    );
    throw new Error(
      errorPayload.success ? (errorPayload.data.error ?? "面试题生成失败") : "面试题生成失败",
    );
  }

  let questions: InterviewQuestion[] | null = null;
  let streamError: string | null = null;

  await readAiRunEventStream(
    response,
    analysisStreamEventSchema,
    (event) => {
      if (event.type === "run.completed") {
        const payload = streamQuestionsPayloadSchema.safeParse(event.output);
        questions = payload.success
          ? payload.data.interviewQuestions.map((question, index) => ({
              ...question,
              order: index + 1,
            }))
          : null;
      } else if (event.type === "run.failed") {
        streamError = event.error.message;
      }
    },
    signal,
  );

  if (streamError) {
    throw new Error(streamError);
  }
  return questions;
}

// oxlint-disable-next-line complexity -- single dialog orchestrates fetch + stream + form + submit; splitting fragments state.
export function HumanInterviewQuestionDialog({
  open,
  recordId,
  candidateName,
  onOpenChange,
  onConfirmed,
}: HumanInterviewQuestionDialogProps) {
  const slug = useWorkspaceSlug();
  const [isGenerating, setIsGenerating] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  // 简历详情：渲染「概览」和「经历」tab，也包含解析 Worker 生成的面试题。
  // Full resume detail backs the tabs and carries worker-generated questions.
  const [resumeDetail, setResumeDetail] = useState<ResumeLibraryDetail | null>(null);
  // 解析阶段没有简历 PDF 可用或自动出题关闭时给出可见的兜底说明。
  // Banner shown when generation is unavailable or disabled.
  const [questionGenerationNotice, setQuestionGenerationNotice] = useState<string | null>(null);
  // 默认停在「面试题」tab；用户可手动切到概览 / 经历查看候选人上下文。
  // Default to the questions tab; users can flip to overview / experience.
  const [activeTab, setActiveTab] = useState<"questions" | "overview" | "experience">("questions");
  const abortControllerRef = useRef<AbortController | null>(null);
  const onConfirmedRef = useRef(onConfirmed);

  useEffect(() => {
    onConfirmedRef.current = onConfirmed;
  }, [onConfirmed]);

  const form = useForm({
    defaultValues: EMPTY_FORM_VALUES,
    onSubmit: async ({ value }) => {
      if (!recordId) {
        return;
      }
      setSubmitting(true);
      await runAsyncAction({
        cleanup: () => setSubmitting(false),
        onError: (error) =>
          toast.error(error instanceof Error ? error.message : "准备真人面试失败"),
        operation: async () => {
          const confirmed = await onConfirmedRef.current(
            normalizeInterviewQuestions(value.interviewQuestions),
          );
          if (confirmed) {
            onOpenChange(false);
          }
        },
      });
    },
  });

  // 弹窗打开时拉简历详情并读取异步生成题目；历史空数据才流式兜底出题。
  // Fetch the resume and use asynchronously generated questions, streaming a
  // fallback only for legacy records; clean up on close or record switch.
  useEffect(() => {
    if (!(open && recordId)) {
      return;
    }
    let cancelled = false;
    const abortController = new AbortController();
    abortControllerRef.current = abortController;
    setQuestionGenerationNotice(null);
    setResumeDetail(null);
    setActiveTab("questions");
    form.reset(EMPTY_FORM_VALUES);

    void runAsyncAction({
      cleanup: () => {
        if (!cancelled) {
          setIsGenerating(false);
        }
      },
      onError: (error) => {
        if (!abortController.signal.aborted) {
          toast.error(error instanceof Error ? error.message : "面试题生成失败");
        }
      },
      operation: async () => {
        const detail = await fetchStudioResume(slug, recordId);
        if (cancelled || abortController.signal.aborted) {
          return;
        }
        setResumeDetail(detail);
        const storedQuestions = getStoredInterviewQuestions(detail);
        if (storedQuestions) {
          form.setFieldValue("interviewQuestions", storedQuestions);
          return;
        }
        const profile = detail?.resumeProfile ?? null;
        if (!env.NEXT_PUBLIC_ENABLE_CANDIDATE_SPECIFIC_INTERVIEW_QUESTIONS) {
          setQuestionGenerationNotice("当前未启用面试题自动生成；可手动添加题目，或直接发起。");
          return;
        }
        if (!profile) {
          setQuestionGenerationNotice(
            "该候选人没有解析过的简历，无法自动生成面试题；可在下方手动添加题目。",
          );
          return;
        }

        setIsGenerating(true);
        const questions = await streamGenerateQuestions(slug, profile, abortController.signal);
        if (cancelled || abortController.signal.aborted) {
          return;
        }
        if (questions && questions.length > 0) {
          form.setFieldValue("interviewQuestions", questions);
          toast.success("面试题已生成，可继续编辑后发起");
        }
      },
    });

    return () => {
      cancelled = true;
      abortController.abort();
    };
    // form is stable from useForm; profile fetch is keyed by open + recordId.
    // oxlint-disable-next-line react-hooks/exhaustive-deps
  }, [open, recordId, slug]);

  const isBusy = isGenerating || submitting;

  return (
    <>
      {/* 与招聘台详情弹窗对齐：Tabs 包住整个 Modal，TabsList 放进 headerExtra；
      内容层横向切换，Modal 高度由自然布局直接决定。 */}
      <Tabs
        key={recordId ?? "empty"}
        onValueChange={(value) => {
          const tab = launchDialogTabSchema.safeParse(value);
          if (tab.success) {
            setActiveTab(tab.data);
          }
        }}
        value={activeTab}
      >
        <Modal
          description={
            candidateName
              ? `确认 ${candidateName} 的面试官参考题，确认后进入真人复面阶段`
              : "确认面试官参考题，确认后进入真人复面阶段"
          }
          dismissible={!isBusy}
          headerExtra={
            // 与详情弹窗 headerExtra 结构对齐：外层 flex row 让 TabsList 在桌面
            // 端按内容自适应；不裸放 TabsList，否则 Modal 的 stack 列容器会把
            // 它拉满宽度。
            // Mirror the detail dialog's headerExtra wrapper so the desktop row
            // sizes TabsList to its content. Rendering TabsList bare inside the
            // modal's stack-mode column would stretch it to 100% width.
            <div className="mt-2 flex flex-col items-stretch gap-3 sm:flex-row sm:flex-wrap sm:items-center sm:justify-between">
              {/* 生成面试题期间锁住所有 tab，避免用户切到「概览/经历」时面试题
                还没准备好，回来一脸空 list；overlay 已经覆盖 body，禁用 tab
                让锁定看起来一致。
                Lock all tabs during question generation so the user can't slip
                away mid-stream — the overlay already blocks the body, this
                keeps the header consistent. */}
              <TabsList className="mt-0 w-full sm:w-auto">
                <TabsTrigger
                  className="flex-1 sm:min-w-[6em] sm:flex-none"
                  disabled={isGenerating}
                  value="questions"
                >
                  面试题
                </TabsTrigger>
                <TabsTrigger
                  className="flex-1 sm:min-w-[6em] sm:flex-none"
                  disabled={isGenerating || !resumeDetail}
                  value="overview"
                >
                  概览
                </TabsTrigger>
                <TabsTrigger
                  className="flex-1 sm:min-w-[6em] sm:flex-none"
                  disabled={isGenerating || !resumeDetail}
                  value="experience"
                >
                  经历
                </TabsTrigger>
              </TabsList>
            </div>
          }
          onOpenChange={(next) => {
            if (!next && isBusy) {
              return;
            }
            onOpenChange(next);
          }}
          open={open}
          showCloseButton={!isBusy}
          size="lg"
          title="准备真人面试"
          footer={
            <div className="flex flex-col gap-2 sm:flex-row sm:justify-end">
              <Button
                disabled={isBusy}
                onClick={() => onOpenChange(false)}
                type="button"
                variant="outline"
              >
                取消
              </Button>
              <Button
                disabled={isBusy}
                onClick={() => {
                  form.handleSubmit();
                }}
                type="button"
              >
                {submitting ? <IconLoader2 className="size-4 animate-spin" /> : null}
                确认并进入真人复面
              </Button>
            </div>
          }
        >
          <div className="relative">
            <TabsContent motion="page" value="questions">
              {questionGenerationNotice ? (
                <Card className="mb-3 gap-0 rounded-md py-0">
                  <CardContent className="bg-muted/40 px-3 py-2 text-muted-foreground text-xs">
                    {questionGenerationNotice}
                  </CardContent>
                </Card>
              ) : null}
              <SortableQuestionListEditor
                arrayFieldName="interviewQuestions"
                contentFieldName="question"
                contentPlaceholder="输入面试题目"
                createItem={(sortIndex) => ({
                  difficulty: "easy",
                  evaluationFocus: "",
                  followUpDirections: "",
                  order: sortIndex + 1,
                  question: "",
                })}
                disabled={isBusy}
                emptyDescription={
                  env.NEXT_PUBLIC_ENABLE_CANDIDATE_SPECIFIC_INTERVIEW_QUESTIONS
                    ? "简历解析完成后会自动填入，也可以手动添加。"
                    : "自动生成已关闭，可以手动添加，也可以留空确认。"
                }
                emptyTitle="暂无面试题"
                form={form}
                resetKey={recordId ?? "new"}
              />
            </TabsContent>

            <TabsContent motion="page" value="overview">
              {resumeDetail ? <ResumeOverviewPanel detail={resumeDetail} /> : null}
            </TabsContent>

            <TabsContent motion="page" value="experience">
              <Card className="gap-0 rounded-2xl border-border bg-background py-0">
                <CardContent className="p-5">
                  <ResumeProfileView profile={resumeDetail?.resumeProfile ?? null} />
                </CardContent>
              </Card>
            </TabsContent>
            {isGenerating ? (
              <m.div
                animate={{ opacity: 1 }}
                className="absolute inset-0 z-50 flex flex-col items-center justify-center gap-3 overflow-y-auto bg-background/85 px-6 py-8 backdrop-blur-sm"
                initial={{ opacity: 0 }}
                transition={{ duration: 0.2 }}
              >
                <IconLoader2 className="size-7 animate-spin text-muted-foreground" />
                <p className="font-medium text-foreground text-sm">正在生成面试题…</p>
                <p className="text-muted-foreground text-xs">
                  生成完成后可继续编辑，确认后会提供给真人面试官参考。
                </p>
              </m.div>
            ) : null}
          </div>
        </Modal>
      </Tabs>
    </>
  );
}

interface LaunchInterviewDialogProps {
  open: boolean;
  recordId: string | null;
  candidateName: string | null;
  onOpenChange: (open: boolean) => void;
  onLaunched: (round: Awaited<ReturnType<typeof launchInterviewFromResume>>) => void;
}

export function LaunchInterviewDialog({
  candidateName,
  onLaunched,
  onOpenChange,
  open,
  recordId,
}: LaunchInterviewDialogProps) {
  const slug = useWorkspaceSlug();
  const [detail, setDetail] = useState<ResumeLibraryDetail | null>(null);
  const [candidateInviteValidity, setCandidateInviteValidity] =
    useState<AiInterviewLinkValidity>("permanent");
  const [isLoading, setIsLoading] = useState(false);
  const [submitting, setSubmitting] = useState(false);

  useEffect(() => {
    if (!(open && recordId)) {
      return;
    }
    let cancelled = false;
    // oxlint-disable-next-line react/set-state-in-effect -- opening on a different record must not display stale evaluation copy.
    setDetail(null);
    // oxlint-disable-next-line react/set-state-in-effect -- each launch starts from the product default regardless of the previous candidate.
    setCandidateInviteValidity("permanent");
    setIsLoading(true);
    void runAsyncAction({
      cleanup: () => {
        if (!cancelled) {
          setIsLoading(false);
        }
      },
      onError: () => {
        if (!cancelled) {
          toast.error("加载候选人信息失败");
        }
      },
      operation: async () => {
        const next = await fetchStudioResume(slug, recordId);
        if (!cancelled) {
          setDetail(next);
        }
      },
    });
    return () => {
      cancelled = true;
    };
  }, [open, recordId, slug]);

  const riskyEvaluation = requiresStructuredLaunchConfirmation(detail);
  let confirmLabel = "确认发起";
  if (isLoading) {
    confirmLabel = "正在确认";
  } else if (submitting) {
    confirmLabel = "正在发起";
  }

  async function handleConfirm() {
    if (!recordId || isLoading || submitting) {
      return;
    }
    setSubmitting(true);
    await runAsyncAction({
      cleanup: () => setSubmitting(false),
      onError: (error) => toast.error(error instanceof Error ? error.message : "发起 AI 面试失败"),
      operation: async () => {
        const round = await launchInterviewFromResume(slug, recordId, {
          candidateInviteValidity,
          structuredEvaluationConfirmation: riskyEvaluation
            ? getStructuredLaunchConfirmation(detail)
            : null,
        });
        toast.success("AI 面试已发起");
        onLaunched(round);
        onOpenChange(false);
      },
    });
  }

  return (
    <AlertDialog onOpenChange={onOpenChange} open={open}>
      <AlertDialogContent>
        <AlertDialogHeader>
          <AlertDialogTitle>确认发起 AI 面试？</AlertDialogTitle>
          <AlertDialogDescription>
            {riskyEvaluation
              ? `AI 评估显示${candidateName ?? "该候选人"}未通过门槛或综合等级为不匹配。该结果仅供参考，确认后仍会创建 AI 面试并将最终筛选状态记为通过。`
              : `确认后将为${candidateName ?? "该候选人"}创建 AI 面试。`}
          </AlertDialogDescription>
        </AlertDialogHeader>
        <Field>
          <FieldLabel htmlFor="ai-interview-link-validity">面试链接有效期</FieldLabel>
          <Select
            disabled={isLoading || submitting}
            onValueChange={(nextValidity) => {
              if (nextValidity) {
                setCandidateInviteValidity(nextValidity);
              }
            }}
            value={candidateInviteValidity}
          >
            <SelectTrigger className="w-full" id="ai-interview-link-validity">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectGroup>
                {AI_INTERVIEW_LINK_VALIDITY_OPTIONS.map((option) => (
                  <SelectItem key={option.value} value={option.value}>
                    {option.label}
                  </SelectItem>
                ))}
              </SelectGroup>
            </SelectContent>
          </Select>
          <FieldDescription>有限有效期从 AI 面试发起成功时开始计算。</FieldDescription>
        </Field>
        <AlertDialogFooter>
          <AlertDialogCancel disabled={submitting}>取消</AlertDialogCancel>
          <AlertDialogAction disabled={isLoading || submitting} onClick={handleConfirm}>
            {submitting ? <IconLoader2 className="size-4 animate-spin" /> : null}
            {confirmLabel}
          </AlertDialogAction>
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>
  );
}
