import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";
import { FeatureBlocks } from "./feature-blocks";

describe("FeatureBlocks", () => {
  it("pairs three close-up editorial scenes with focused recruiting UI", () => {
    const markup = renderToStaticMarkup(<FeatureBlocks />);

    expect(markup).toContain('data-feature-story="evidence"');
    expect(markup).toContain('data-feature-story="interview"');
    expect(markup).toContain('data-feature-story="calibration"');
    expect(markup).toContain('data-feature-story="evidence" data-layout="copy-visual"');
    expect(markup).toContain('data-feature-story="interview" data-layout="visual-copy"');
    expect(markup).toContain('data-feature-story="calibration" data-layout="copy-visual"');
    expect(markup.match(/data-visual-position="bottom-right"/g)).toHaveLength(1);
    expect(markup.match(/data-visual-position="bottom-left"/g)).toHaveLength(1);
    expect(markup.match(/data-visual-position="top-right"/g)).toHaveLength(1);
    expect(markup.match(/p-\[6px\]/g)).toHaveLength(2);
    expect(markup.match(/data-visual-inset="relaxed"/g)).toHaveLength(1);
    expect(markup.match(/data-visual-inset="edge"/g)).toHaveLength(2);
    expect(markup).toContain("/landing/feature-scenes/evidence-review-v2.jpg");
    expect(markup).toContain("/landing/feature-scenes/evidence-review-dark-v2.jpg");
    expect(markup).toContain("/landing/feature-scenes/interview-conversation.jpg");
    expect(markup).toContain("/landing/feature-scenes/interview-conversation-dark.jpg");
    expect(markup).toContain("/landing/feature-scenes/team-calibration.jpg");
    expect(markup).toContain("/landing/feature-scenes/team-calibration-dark.jpg");
    expect(markup.match(/type="image\/avif"/g)).toHaveLength(6);
    expect(markup.match(/type="image\/webp"/g)).toHaveLength(6);
    expect(markup).toContain("/landing/optimized/feature-scenes/evidence-review-v2.avif");
    expect(markup).toContain(
      "/landing/optimized/feature-scenes/evidence-review-v2-1024.avif 1024w",
    );
    expect(markup.match(/sizes="\(min-width: 1024px\) 60vw, 100vw"/g)).toHaveLength(18);
    expect(markup.match(/loading="lazy"/g)).toHaveLength(6);
    expect(markup.match(/data-artwork-theme="light"/g)).toHaveLength(3);
    expect(markup.match(/data-artwork-theme="dark"/g)).toHaveLength(3);
    expect(markup).toContain('data-slot="candidate-score-card"');
    expect(markup).toContain('data-alignment="centered"');
    expect(markup).toContain("content-center");
    expect(markup).toContain("height:156px");
    expect(markup).toContain('viewBox="0 0 640 156"');
    expect(markup).toContain('data-mobile-layout="radar-scores"');
    expect(markup).toContain('data-slot="candidate-score-radar"');
    expect(markup.match(/data-score-dimension=/g)).toHaveLength(6);
    expect(markup).toContain("技能匹配度");
    expect(markup).toContain("经验相关性");
    expect(markup).toContain("项目匹配度");
    expect(markup).toContain("学历/背景");
    expect(markup).toContain("潜力评估");
    expect(markup).toContain("稳定性评估");
    expect(markup).toContain('data-slot="interview-composer"');
    expect(markup).toContain('data-density="compact"');
    expect(markup.match(/data-message-role=/g)).toHaveLength(4);
    expect(markup.match(/data-message-role="user"/g)).toHaveLength(2);
    expect(markup.match(/data-message-role="assistant"/g)).toHaveLength(2);
    expect(markup).toContain("明日香在复杂前端项目里，具体负责过什么？");
    expect(markup).toContain("她本人承担了哪些关键决策？");
    expect(markup).toContain("证据来自简历第 2 页和面试回答 12:36");
    expect(markup).toContain("继续询问明日香的项目经历、能力证据或风险…");
    expect(markup).toContain('data-slot="team-calibration-card"');
    expect(markup).toContain('data-slot="team-calibration-metrics"');
    expect(markup).toContain('data-layout="horizontal"');
    expect(markup.match(/data-mobile-height="compact"/g)).toHaveLength(2);
    expect(markup.match(/data-mobile-height="default"/g)).toHaveLength(1);
    expect(markup).not.toContain("data-home-scene");
    expect(markup).not.toContain("data-window-control");
    expect(markup).not.toContain("Recruiting Copilot");
    expect(markup).not.toContain("Resume Screening");
    expect(markup).not.toContain("Interview Copilot");
    expect(markup).not.toContain("Team Calibration");
    expect(markup.match(/text-balance/g)).toHaveLength(4);
  });
});
