import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { API_DOMAIN_BY_TAG, isApiTag } from "./api-domain.js";

interface OpenApiOperation {
  operationId?: string;
  tags?: string[];
}

interface OpenApiDocument {
  paths: Record<string, Record<string, OpenApiOperation>>;
}

describe("OpenAPI domain map", () => {
  it("assigns every generated operation to one stable frontend domain", async () => {
    const openApiPath = resolve(import.meta.dirname, "../../openapi.json");
    const source = await readFile(openApiPath, "utf-8");
    // SAFETY: openapi.json is generated by this application and the test only reads its paths/operation metadata.
    const document = JSON.parse(source) as OpenApiDocument;
    const unmapped: string[] = [];
    let operationCount = 0;

    for (const [path, pathItem] of Object.entries(document.paths)) {
      for (const [method, operation] of Object.entries(pathItem)) {
        if (!operation.operationId) {
          continue;
        }
        operationCount += 1;
        const domains = new Set(
          (operation.tags ?? [])
            .map((tag) => (isApiTag(tag) ? API_DOMAIN_BY_TAG[tag] : undefined))
            .filter(Boolean),
        );
        if (domains.size !== 1) {
          unmapped.push(
            `${method.toUpperCase()} ${path} (${operation.tags?.join(",") ?? "no tag"})`,
          );
        }
      }
    }

    expect(operationCount).toBe(333);
    expect(unmapped).toEqual([]);
  });
});
